from __future__ import annotations
from typing import Protocol
from .types import PlatformPost, PlatformComment, PlatformAccount


class ScraperProtocol(Protocol):
    async def scrape_post(self, url: str) -> PlatformPost: ...
    async def scrape_profile(self, account_id: str) -> PlatformAccount: ...
    async def scrape_comments(self, post_id: str) -> list[PlatformComment]: ...
    async def check_login_status(self) -> bool: ...
    async def login(self, method: str = "qrcode") -> None: ...
